(defproject infowarss "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.8.0"]
                 [org.clojure/tools.nrepl "0.2.13"]
                 [clj-http "3.5.0"]
                 [org.clojure/core.async "0.3.442"]
                 [slingshot "0.12.2"]
                 [hickory "0.7.1"]
                 [clojurewerkz/serialism "1.3.0"]
                 [clj-rome "0.4.0"]
                 [digest "1.4.5"]
                 [table "0.5.0"]
                 [matchbox "0.0.9"]
                 [com.taoensso/timbre "4.10.0"]
                 [org.slf4j/log4j-over-slf4j "1.7.25"]
                 [org.slf4j/jul-to-slf4j "1.7.25"]
                 [org.slf4j/jcl-over-slf4j "1.7.25"]
                 [com.fzakaria/slf4j-timbre "0.3.5"]
                 [clojurewerkz/quartzite "2.0.0"]
                 [twitter-api "1.8.0"]
                 [com.draines/postal "2.0.2"]
                 [ring/ring-core "1.5.1"]
                 [compojure "1.5.2"]
                 [liberator "0.14.1"]
                 [prismatic/schema-generators "0.1.0"]
                 [prismatic/schema "1.1.5"]
                 [ring/ring-devel "1.5.1"]
                 [ring/ring-jetty-adapter "1.5.1"]
                 [ring/ring-json "0.4.0"]cl                 [ring/ring-mock "0.3.0"]

                 [lambda-ml "0.1.0"]
                 [clojure-opennlp "0.4.0"]
                 [im.chit/hara.io.scheduler "2.5.2"]
                 [ring/ring-mock "0.3.0"]
                 [ring-basic-authentication "1.0.5"]
                 [com.ashafa/clutch "0.4.0"]
                 [com.firebase/firebase-client-jvm "2.5.2"]
                 [clj-time "0.13.0"]])
