version: '3.8'
services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: changeme
    volumes:
      - llar-postgresql:/var/lib/postgresql/data
      - ./initdb.d:/docker-entrypoint-initdb.d
    shm_size: '246MB'
  llar-init-db:
    image: ghcr.io/irq0/llar:latest
    user: root
    links:
      - db
    depends_on:
      db:
        condition: service_started
    volumes:
      - llar-state:/llar
      - llar-blobstore:/llar/blobs
      - ../config:/llar/config/
      - ./docker-config.edn:/llar/config.edn
      - ./credentials.edn:/llar/credentials.edn
    entrypoint:
      - "/bin/bash"
      - "-c"
      - >
        set -x;
        if [[ -r "/llar/db-initialized" ]]; then
           exit 0
        fi;
        sleep 5;
        chown -R llar:llar /llar/blobs;
        chmod u+w /llar/blobs;
        if java -jar /opt/llar/standalone.jar --init-db; then
           date -u +"%Y-%m-%dT%H:%M:%SZ" > /llar/db-initialized;
        else
           set +x
           echo "Database initialization failed :("
           exit 23
        fi;
    environment:
      LLAR_CONFIG: /llar/config.edn
  llar:
    image: ghcr.io/irq0/llar:latest
    user: llar
    links:
      - db
    depends_on:
      db:
        condition: service_started
      llar-init-db:
        condition: service_completed_successfully
    volumes:
      - llar-state:/llar
      - llar-blobstore:/llar/blobs
      - ../config:/llar/config/
      - ./docker-config.edn:/llar/config.edn
      - ./credentials.edn:/llar/credentials.edn
    mem_limit: 4g
    ports:
      - "8023:8023"
      - "9999:9999"
      - "42000:42000"
    environment:
      LLAR_CONFIG: /llar/config.edn

volumes:
  llar-postgresql:
  llar-blobstore:
  llar-state:
