#!/bin/bash

set -e
set -x

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER llar WITH PASSWORD 'changeme';
	CREATE DATABASE llar OWNER llar;
	GRANT ALL PRIVILEGES ON DATABASE llar TO llar;
	GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO llar;
	GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO llar;
EOSQL
